version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  labels:
  - "category: engineering"
  - dependencies
  versioning-strategy: widen
  ignore:
  - dependency-name: axe-core
    versions:
    - ">= 0"
  - dependency-name: "@types/node"
    versions:
    - 14.14.30
    - 15.0.0
    - 15.0.1
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: npm
  directory: "/src/test-resources/generator"
  schedule:
    interval: daily
    time: "13:00"
  labels:
  - "category: engineering"
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: axe-core
    versions:
    - ">= 0"
  - dependency-name: "@axe-core/puppeteer"
    versions:
    - ">= 0"
  - dependency-name: "@types/node"
    versions:
    - 14.14.30
    - 15.0.0
  - dependency-name: puppeteer
    versions:
    - 8.0.0
  commit-message:
    prefix: chore
    include: scope
