# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.5.0.cjs
npmRegistryServer: "https://pkgs.dev.azure.com/mseng/1ES/_packaging/A11yAgent_PublicPackages/npm/registry/"
