# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
npmRegistryServer: 'https://pkgs.dev.azure.com/accessibility-insights-private/c79273f4-2dcc-480f-852b-0267a30c82db/_packaging/a11y-insights-public/npm/registry/'
npmAlwaysAuth: true

nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.5.0.cjs
