# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
jobs:
    - job: 'tests_and_checks'

      pool:
          vmImage: 'ubuntu-16.04'

      steps:
          - task: NodeTool@0
            inputs:
                versionSpec: '10.15.3'
            displayName: use node 10.15.3

          - script: yarn install --frozen-lockfile
          - script: yarn lint
          - script: yarn format-check
          - script: yarn copyrightheaders
          - script: yarn test -- --ci

          - task: PublishTestResults@2
            inputs:
                testResultsFiles: $(System.DefaultWorkingDirectory)/test-results/junit.xml
                testRunTitle: axe-sarif-converter
            condition: always()
            displayName: publish test results

          - task: PublishCodeCoverageResults@1
            inputs:
                codeCoverageTool: Cobertura
                summaryFileLocation: $(System.DefaultWorkingDirectory)/test-results/coverage/cobertura-coverage.xml
                failIfCoverageEmpty: true
            displayName: publish code coverage

          - task: PublishBuildArtifacts@1
            inputs:
                pathtoPublish: '$(System.DefaultWorkingDirectory)/test-results/test_result.sarif'
                artifactName: 'CodeAnalysisLogs'
            condition: always()
            displayName: publish sarif results

          - script: yarn build

          - script: yarn semantic-release
            displayName: yarn semantic-release (master branch only)
            env:
                GH_TOKEN: $(GH_TOKEN)
                NPM_TOKEN: $(NPM_TOKEN)
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['EnableSemanticRelease'], 'true'))
