# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
variables:
    Codeql.Enabled: true

jobs:
    - job: 'tests_and_checks'

      pool:
          vmImage: 'ubuntu-22.04'

      steps:
          # This is later than the minimum version the package claims support
          # for because semantic-release requires a later LTS version that we
          # can require of our users without a breaking change
          - task: NodeTool@0
            inputs:
                versionSpec: '14.18.3'
            displayName: use node 14.18.3

          - script: yarn install --immutable
            displayName: yarn install

          - script: yarn lint
            displayName: yarn lint

          - script: yarn format-check
            displayName: yarn format-check

          - script: yarn copyrightheaders
            displayName: yarn copyrightheaders

          - script: yarn build
            displayName: yarn build

          - script: yarn test --ci
            displayName: yarn test

          - task: PublishTestResults@2
            inputs:
                testResultsFiles: $(System.DefaultWorkingDirectory)/test-results/junit.xml
                testRunTitle: axe-sarif-converter
            condition: always()
            displayName: publish test results

          - task: PublishCodeCoverageResults@1
            inputs:
                codeCoverageTool: Cobertura
                summaryFileLocation: $(System.DefaultWorkingDirectory)/test-results/coverage/cobertura-coverage.xml
                failIfCoverageEmpty: true
            displayName: publish code coverage

          - task: PublishBuildArtifacts@1
            inputs:
                pathtoPublish: '$(System.DefaultWorkingDirectory)/test-results/'
                artifactName: 'CodeAnalysisLogs'
            condition: always()
            displayName: publish sarif results

          - script: yarn semantic-release
            displayName: yarn semantic-release (main branch only)
            env:
                GH_TOKEN: $(github-ada-cat-auth-token)
                NPM_TOKEN: $(npmjs-accessibility-insights-team-publish-auth-token)
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['EnableSemanticRelease'], 'true'))
