version: 1
update_configs:
    - package_manager: 'javascript'
      directory: '/'
      update_schedule: 'daily'
      version_requirement_updates: 'widen_ranges'
      default_labels:
          - 'category: engineering'
          - 'dependencies'
      commit_message:
          prefix: 'chore'
          include_scope: true
      # axe updates require specific manual steps; see /README.md
      ignored_updates:
          - match:
                dependency_name: 'axe-core'
    - package_manager: 'javascript'
      directory: '/src/test-resources/generator'
      update_schedule: 'daily'
      version_requirement_updates: 'increase_versions'
      default_labels:
          - 'category: engineering'
          - 'dependencies'
      commit_message:
          prefix: 'chore'
          include_scope: true
      # axe updates require specific manual steps; see /README.md
      ignored_updates:
          - match:
                dependency_name: 'axe-core'
          - match:
                dependency_name: '@axe-core/puppeteer'
